alter table public.addon_templates
    add column if not exists is_customer_visible boolean not null default true;

comment on column public.addon_templates.is_customer_visible is
    'True for customer-selectable add-ons; false for admin-only charges such as transport.';

create table if not exists public.customer_addon_packages (
    id integer generated by default as identity primary key,
    customer_addon_id integer not null references public.customer_addons(id) on delete cascade,
    customer_package_id integer not null references public.customer_packages(id) on delete cascade,
    constraint uq_customer_addon_package unique (customer_addon_id, customer_package_id)
);

create index if not exists ix_customer_addon_packages_customer_addon_id
    on public.customer_addon_packages(customer_addon_id);

create index if not exists ix_customer_addon_packages_customer_package_id
    on public.customer_addon_packages(customer_package_id);

alter table public.customer_addon_packages enable row level security;
revoke all on table public.customer_addon_packages from public, anon, authenticated;
