alter table public.customers
    add column if not exists order_cutoff_day_offset integer not null default 1,
    add column if not exists order_cutoff_time varchar(5) not null default '18:00';

alter table public.customers
    drop constraint if exists customers_order_cutoff_day_offset_check,
    add constraint customers_order_cutoff_day_offset_check
        check (order_cutoff_day_offset in (0, 1)),
    drop constraint if exists customers_order_cutoff_time_check,
    add constraint customers_order_cutoff_time_check
        check (order_cutoff_time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$');

create table if not exists public.customer_order_cutoff_overrides (
    id integer generated by default as identity primary key,
    customer_id integer not null references public.customers(id) on delete cascade,
    delivery_date date not null,
    cutoff_at timestamptz not null,
    reason text not null,
    updated_by varchar(100) not null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamptz,
    constraint uq_customer_delivery_cutoff_override unique (customer_id, delivery_date)
);

create index if not exists ix_customer_order_cutoff_overrides_customer_id
    on public.customer_order_cutoff_overrides(customer_id);
create index if not exists ix_customer_order_cutoff_overrides_delivery_date
    on public.customer_order_cutoff_overrides(delivery_date);

alter table public.customer_order_cutoff_overrides enable row level security;
revoke all on table public.customer_order_cutoff_overrides from public, anon, authenticated;
