alter table public.orders
    add column if not exists do_number varchar(50);

update public.orders
set do_number = 'DO-' || to_char(delivery_date, 'YYYYMMDD') || '-' || lpad(id::text, 4, '0')
where do_number is null;

create unique index if not exists ux_orders_do_number
    on public.orders(do_number);

create table if not exists public.whatsapp_settings (
    id integer primary key default 1 check (id = 1),
    gateway_url varchar(500) not null default '',
    session_name varchar(100) not null default 'default',
    api_key_encrypted text,
    is_enabled boolean not null default false,
    updated_by varchar(100),
    updated_at timestamptz
);

create table if not exists public.customer_whatsapp_groups (
    id integer generated by default as identity primary key,
    customer_id integer not null unique references public.customers(id) on delete cascade,
    group_id varchar(200) not null,
    group_name varchar(200) not null,
    is_enabled boolean not null default true,
    show_prices boolean not null default false,
    verified_at timestamptz,
    updated_by varchar(100),
    updated_at timestamptz
);

create index if not exists ix_customer_whatsapp_groups_customer_id
    on public.customer_whatsapp_groups(customer_id);
create unique index if not exists ux_customer_whatsapp_groups_group_id
    on public.customer_whatsapp_groups(group_id);

create table if not exists public.whatsapp_deliveries (
    id integer generated by default as identity primary key,
    order_id integer not null references public.orders(id) on delete cascade,
    order_version integer not null,
    event_type varchar(30) not null,
    dedupe_key varchar(200) not null unique,
    group_id varchar(200) not null,
    group_name varchar(200) not null,
    show_prices boolean not null default false,
    message_text text,
    status varchar(30) not null default 'pending',
    attempt_count integer not null default 0,
    gateway_message_id varchar(300),
    last_error text,
    requested_by varchar(100) not null,
    request_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    sent_at timestamptz,
    delivered_at timestamptz,
    read_at timestamptz
);

create index if not exists ix_whatsapp_deliveries_order_id
    on public.whatsapp_deliveries(order_id);
create index if not exists ix_whatsapp_deliveries_status
    on public.whatsapp_deliveries(status);
create index if not exists ix_whatsapp_deliveries_gateway_message_id
    on public.whatsapp_deliveries(gateway_message_id);

alter table public.whatsapp_settings enable row level security;
alter table public.customer_whatsapp_groups enable row level security;
alter table public.whatsapp_deliveries enable row level security;

revoke all on table public.whatsapp_settings from public, anon, authenticated;
revoke all on table public.customer_whatsapp_groups from public, anon, authenticated;
revoke all on table public.whatsapp_deliveries from public, anon, authenticated;
